### ISSUE TITLE
list must have an even number of elements

### ISSUE THREAD

**Issue by gjosang** [mhum/pia-transmission-updater#1]
Having some issue running it. 

Running: tclsh updater.tcl
list must have an even number of elements
    while executing
"http::geturl $trans_url -query $query -headers $headers"
    invoked from within
"set resp_token [http::geturl $trans_url -query $query -headers $headers]"
    (file "updater.tcl" line 24)

Any idea what it could be? 
I'am running on ubuntu 14.04.4 headless server.

**Comment by mhum** [comment]
Hi @gjosang,

The error occurs on the line where the request is formatted in preparation for asking Transmission if its port is open. To make any requests to Transmission, a CSRF token needs to be sent along. That's retrieved first and sent as part of the $headers variable (which is the bit than needs to be an even list).

I suspect the CSRF token isn't being retrieved for some reason from Transmission. I added a check that will verify if the CSRF token is blank and then output the response from Transmission if it is blank. 

Would you mind pulling down the update on master and giving it another go?

**Comment by gjosang** [comment]
Hi @mhum 
Thanks for the quick response. 
Sadly I still get the same error.. 

list must have an even number of elements
    while executing
"http::geturl $trans_url -query $query -headers $headers"
    invoked from within
"set resp_token [http::geturl $trans_url -query $query -headers $headers]"
    (file "./updater.tcl" line 32)

I tried reinstalling tcl and tcllib.. 

Tcl info: 
tcl8.6 
% package require http
2.8.7
% package require json
1.1.2
Transmission 2.92

**Comment by mhum** [comment]
Interesting. Very similar setup to me. I still think there is some issue fetching the CSRF token. I've pushed some changes to add a debug mode to output more verbose logs.

Pull down the latest and append '--debug true' when running ./updater.tcl so the command becomes:
`./updater.tcl --debug true`

**Comment by gjosang** [comment]
Here is the output from --degbug true: 

DEBUG: Connecting to transmission at: http://localhost:9091
DEBUG: Response received:
DEBUG: Server Transmission WWW-Authenticate {Basic realm="Transmission"} Date {Thu, 21 Apr 2016 17:16:02 GMT} Content-Length 43 Content-Type {text/html; charset=ISO-8859-1} Connection close
DEBUG: Retrieved CSRF token: Basic realm="Transmission"
DEBUG: Send query: {"arguments": {},"method": "port-test"}
DEBUG: With headers: X-Transmission-Session-Id Basic realm="Transmission"
DEBUG: To http://localhost:9091
list must have an even number of elements
    while executing
"http::geturl $trans_url -query $query -headers $headers"
    invoked from within
"set resp_token [http::geturl $trans_url -query $query -headers $headers]"
    (file "./updater.tcl" line 73)

**Comment by mhum** [comment]
Interesting. It does have to do with the CSRF token as I suspected. `DEBUG: With headers: X-Transmission-Session-Id Basic realm="Transmission"` is the reason for the tcl error.

It should look something like this when running correctly:

> ./updater.tcl --debug true
> DEBUG: Connecting to transmission at: http://localhost:9091/transmission/rpc
> DEBUG: Response received:
> DEBUG: Server Transmission X-Transmission-Session-Id 8ajPL53JHcnNweQ8SNwJT9V69pziNMbCNtX0IF3Zgh8cd93E Date {Thu, 21 Apr 2016 23:11:19 GMT} Content-Length 580 Content-Type {text/html; charset=ISO-8859-1} Connection close
> DEBUG: Retrieved CSRF token: 8ajPL53JHcnNweQ8SNwJT9V69pziNMbCNtX0IF3Zgh8cd93E
> DEBUG: Send query: {"arguments": {},"method": "port-test"}
> DEBUG: With headers: X-Transmission-Session-Id 8ajPL53JHcnNweQ8SNwJT9V69pziNMbCNtX0IF3Zgh8cd93E
> DEBUG: To http://localhost:9091/transmission/rpc
> DEBUG: Received: arguments {port-is-open true} result success
> DEBUG: Port open: true
> Port is still open

You need to change the URL to add `/transmission/rpc` to the end. Communication with Transmission is through it's RPC API.

**Comment by gjosang** [comment]
Hmm.. 
I tried that earlier and i get the same error: 
DEBUG: Connecting to transmission at: http://localhost:9091/transmission/rpc
DEBUG: Response received:
DEBUG: Server Transmission WWW-Authenticate {Basic realm="Transmission"} Date {Fri, 22 Apr 2016 06:57:08 GMT} Content-Length 43 Content-Type {text/html; charset=ISO-8859-1} Connection close
DEBUG: Retrieved CSRF token: Basic realm="Transmission"
DEBUG: Send query: {"arguments": {},"method": "port-test"}
DEBUG: With headers: X-Transmission-Session-Id Basic realm="Transmission"
DEBUG: To http://localhost:9091/transmission/rpc
list must have an even number of elements
    while executing
"http::geturl $trans_url -query $query -headers $headers"
    invoked from within
"set resp_token [http::geturl $trans_url -query $query -headers $headers]"
    (file "./updater.tcl" line 73)

How does you transmission settings.json look like?

**Comment by mhum** [comment]
> {
>     "alt-speed-down": 100,
>     "alt-speed-enabled": false,
>     "alt-speed-time-begin": 540,
>     "alt-speed-time-day": 2,
>     "alt-speed-time-enabled": false,
>     "alt-speed-time-end": 1020,
>     "alt-speed-up": 25,
>     "bind-address-ipv4": "0.0.0.0",
>     "bind-address-ipv6": "::",
>     "blocklist-enabled": false,
>     "blocklist-url": "",
>     "cache-size-mb": 4,
>     "dht-enabled": true,
>     "download-dir": "/mnt/new",
>     "download-limit": 100,
>     "download-limit-enabled": 0,
>     "download-queue-enabled": true,
>     "download-queue-size": 5,
>     "encryption": 1,
>     "idle-seeding-limit": 30,
>     "idle-seeding-limit-enabled": true,
>     "incomplete-dir": "",
>     "incomplete-dir-enabled": false,
>     "lpd-enabled": false,
>     "max-peers-global": 200,
>     "message-level": 2,
>     "peer-congestion-algorithm": "",
>     "peer-id-ttl-hours": 6,
>     "peer-limit-global": 500,
>     "peer-limit-per-torrent": 100,
>     "peer-port": 26404,
>     "peer-port-random-high": 65535,
>     "peer-port-random-low": 49152,
>     "peer-port-random-on-start": false,
>     "peer-socket-tos": "default",
>     "pex-enabled": true,
>     "port-forwarding-enabled": false,
>     "preallocation": 1,
>     "prefetch-enabled": true,
>     "queue-stalled-enabled": true,
>     "queue-stalled-minutes": 30,
>     "ratio-limit": 1.5000,
>     "ratio-limit-enabled": true,
>     "rename-partial-files": true,
>     "rpc-authentication-required": false,
>     "rpc-bind-address": "0.0.0.0",
>     "rpc-enabled": true,
>     "rpc-password": "",
>     "rpc-port": 9091,
>     "rpc-url": "/transmission/",
>     "rpc-username": "transmission",
>     "rpc-whitelist": "127.0.0.1",
>     "rpc-whitelist-enabled": false,
>     "scrape-paused-torrents-enabled": true,
>     "script-torrent-done-enabled": false,
>     "script-torrent-done-filename": "",
>     "seed-queue-enabled": false,
>     "seed-queue-size": 10,
>     "speed-limit-down": 100,
>     "speed-limit-down-enabled": false,
>     "speed-limit-up": 500,
>     "speed-limit-up-enabled": true,
>     "start-added-torrents": true,
>     "trash-original-torrent-files": false,
>     "umask": 18,
>     "upload-limit": 100,
>     "upload-limit-enabled": 0,
>     "upload-slots-per-torrent": 14,
>     "utp-enabled": true
> }

**Comment by gjosang** [comment]
I got it working 👍 
"rpc-authentication-required": false did the trick. 
Mine was set to true, pretty sure i check that last night but i guess not... 

Thank you for the help @mhum :-)

**Comment by mhum** [comment]
Awesome! Glad it works now!
