### ISSUE TITLE
Cron 

### ISSUE THREAD

**Issue by gjosang** [mhum/pia-transmission-updater#2]
Hei @mhum 

The script work great, but I'am having trouble scheduling it.. 
I have not much experience with tcl.. So i may be doing something wrong..
I have set up this cron: 
@hourly /usr/bin/tclsh /opt/scripts/updater.tcl

From logs i see this: 
Date: Sat, 23 Apr 2016 22:58:01 +0200 (CEST)

Port is no longer open. Let's continue!
couldn't execute "ifconfig": no such file or directory
    while executing
"exec ifconfig $device"
    invoked from within
"regexp {inet .*?(10.[0-9]+.[0-9]+.[0-9]+)} [exec ifconfig $device] -> local_ip"
    (file "/opt/scripts/updater.tcl" line 114)

Running /usr/bin/tclsh /opt/scripts/updater.tcl from command line works just fint. 

How have you set up your cron? 
Is there some tcl environment thing I have to change?

**Comment by mhum** [comment]
Crontab runs with a different environment than users, so not everything that is available on the PATH to the user is available on the PATH to cron jobs. I set up the environment that I want at the top of my crontab and then run the script:

```
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

@hourly cd /home/nas/scripts/pia-transmission-updater && /usr/bin/tclsh updater.tcl > /var/log/cron 2>&1
```

**Comment by gjosang** [comment]
Again thank you @mhum
