### ISSUE TITLE
Trouble with latest release

### ISSUE THREAD

**Issue by gjosang** [mhum/pia-transmission-updater#3]
Do you have any suggestion regarding this error? 

DEBUG: Received: arguments {port-is-open false} result success
DEBUG: Port open: false
Port is no longer open. Let's continue!
DEBUG: Read client id from: /home/user/.pia_client_id
DEBUG: Client id: 

DEBUG: Run ifconfig for tun0:
tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.133.1.6  P-t-P:10.133.1.5  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:47611175 errors:0 dropped:0 overruns:0 frame:0
          TX packets:56266484 errors:0 dropped:140397 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:29744413819 (29.7 GB)  TX bytes:63441025372 (63.4 GB)

DEBUG: Found IP: 10.133.1.6
DEBUG: Format query to fetch port: 
DEBUG: Sending to: http://www.privateinternetaccess.com/vpninfo/port_forward_assignment
DEBUG: Response:
DEBUG: error {Invalid parameter: client_id}
key "port" not known in dictionary
    while executing
"dict get $resp port"
    (procedure "::upd::updPia::fetchPort" line 41)
    invoked from within
"::upd::updPia::fetchPort"
    invoked from within
"set port [::upd::updPia::fetchPort]"
    (file "./updater.tcl" line 40)

**Comment by mhum** [comment]
I've pushed a fix for this. 

It looks like PIA starting validating the client id format and I wasn't trimming the extra whitespace at the end after reading it from the file; I've changed it to trim the whitespace now.

**Comment by gjosang** [comment]
@mhum perfect working fine now!
